theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
